In [1]:
import numpy as np

In [4]:
arreglo_numeros = np.array([1, 2, 3])
print(arreglo_numeros)

[1 2 3]


In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
np.ones(5)
np.ones((5,3))
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
np.empty(5)
np.empty((3,2))
np.empty((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [16]:
print(np.eye(4))
print(np.eye(5))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
print(np.arange(12))
print(np.arange(3,50))
print(np.arange(3,50,10))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[ 3 13 23 33 43]


In [25]:
arreglo_dimension = np.array([(1,2,3),(4,5,6)])
arreglo_dimension.shape

(2, 3)

In [30]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [34]:
print(np.ones_like(np.arange(6).reshape(3,2)))
print(np.ones_like(np.arange(3)))

[[1 1]
 [1 1]
 [1 1]]
[1 1 1]


In [40]:
np.arange(24).reshape(6,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [46]:
np.arange(10000).reshape(100,10,10)

array([[[   0,    1,    2, ...,    7,    8,    9],
        [  10,   11,   12, ...,   17,   18,   19],
        [  20,   21,   22, ...,   27,   28,   29],
        ...,
        [  70,   71,   72, ...,   77,   78,   79],
        [  80,   81,   82, ...,   87,   88,   89],
        [  90,   91,   92, ...,   97,   98,   99]],

       [[ 100,  101,  102, ...,  107,  108,  109],
        [ 110,  111,  112, ...,  117,  118,  119],
        [ 120,  121,  122, ...,  127,  128,  129],
        ...,
        [ 170,  171,  172, ...,  177,  178,  179],
        [ 180,  181,  182, ...,  187,  188,  189],
        [ 190,  191,  192, ...,  197,  198,  199]],

       [[ 200,  201,  202, ...,  207,  208,  209],
        [ 210,  211,  212, ...,  217,  218,  219],
        [ 220,  221,  222, ...,  227,  228,  229],
        ...,
        [ 270,  271,  272, ...,  277,  278,  279],
        [ 280,  281,  282, ...,  287,  288,  289],
        [ 290,  291,  292, ...,  297,  298,  299]],

       ...,

       [[9700, 9701, 970

In [47]:
# Sumas
a = np.array([10, 10, 10])
b = np.array([5, 5, 5])
a + b

array([15, 15, 15])

In [49]:
# Resta
a - b

array([5, 5, 5])

In [50]:
# Multiplicación
a * b

array([50, 50, 50])

In [52]:
#  División
a / b

array([2., 2., 2.])

In [54]:
# Operaciones
arreglo_diez_ocho = np.arange(18)
print(arreglo_diez_ocho/2)
print(arreglo_diez_ocho%2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]


In [55]:
# Expresiones
arreglo_diez_ocho > 9

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True])

In [75]:
# Multiplicación de varias dimensiones
A = np.arange(4).reshape(2,2)
print(A)
B = np.arange(4,8).reshape(2,2)
print(B)
A < B

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


array([[ True,  True],
       [ True,  True]])

In [ ]:
# Moltiplicación dot

In [77]:
print(np.dot(A, B))
A.dot(B)

[[ 6  7]
 [26 31]]


array([[ 6,  7],
       [26, 31]])

In [79]:
arreglo_tres = np.arange(3)
print(arreglo_tres)
arreglo_tres += 3
print(arreglo_tres)

[0 1 2]
[3 4 5]


In [80]:
# Operaciones conocidos en los arreglos
arreglo_diez_elementos = np.arange(10)
print(arreglo_diez_elementos)
print(arreglo_diez_elementos.sum())
print(arreglo_diez_elementos.min())
print(arreglo_diez_elementos.max())

[0 1 2 3 4 5 6 7 8 9]
45
0
9


In [83]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)
print(arreglo_tres_cuatro)
print(arreglo_tres_cuatro.sum(axis=0))  # X
print(arreglo_tres_cuatro.sum(axis=1))  # Y

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


# Universal Functions
## Radianes

In [103]:
angulos_cero_noventa = np.array([0, 30, 45, 60, 90])
print(angulos_cero_noventa)
angulos_cero_noventa_radianes = angulos_cero_noventa * np.pi/180
print(angulos_cero_noventa_radianes)
angulos_cero_noventa_radianes = np.deg2rad(angulos_cero_noventa)
print(angulos_cero_noventa_radianes)
print(np.pi)

[ 0 30 45 60 90]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
3.141592653589793


In [88]:
# Función seno
print(np.sin(angulos_cero_noventa))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]


In [89]:
# Función coseno
print(np.cos(angulos_cero_noventa))

[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]


In [90]:
# Función tangente
print(np.tan(angulos_cero_noventa))

[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


In [101]:
# Media
print(np.mean(np.random.rand(10)*10))

4.859547771971603


In [100]:
# Media
print(np.median(np.random.rand(10)*10))

7.816723030265859


In [105]:
# Desviación Estandar
print(arreglo_diez_elementos)
print(np.std(arreglo_diez_elementos))

[0 1 2 3 4 5 6 7 8 9]
2.8722813232690143


In [104]:
# Varianza
print(arreglo_diez_elementos)
print(np.var(arreglo_diez_elementos))

[0 1 2 3 4 5 6 7 8 9]
8.25


In [108]:
# salarios
salarios = np.genfromtxt('data/salarios.csv', delimiter=',')
print(salarios)
print(salarios.shape)

[[ 1. 10. 15.  4.  3.  6. 18. 20.  7. 14.]
 [ 1. 10. 15.  4.  3.  6. 18. 20.  7. 14.]
 [ 1. 10. 15.  4.  3.  6. 18. 20.  7. 14.]]
(3, 10)


In [131]:
# Slicing and Dice
arreglo_once_cuadrado = np.arange(11)**2
print(arreglo_once_cuadrado)
print(arreglo_once_cuadrado[0:3])
print(arreglo_once_cuadrado[-3])
print(arreglo_once_cuadrado[2:-3])
print(arreglo_once_cuadrado[-8:-1])
print(arreglo_once_cuadrado[1:])
print(arreglo_once_cuadrado[:5])
print(arreglo_once_cuadrado[2:8:4])
print(arreglo_once_cuadrado[:10:2])
print(arreglo_once_cuadrado[::-1])

[  0   1   4   9  16  25  36  49  64  81 100]
[0 1 4]
64
[ 4  9 16 25 36 49]
[ 9 16 25 36 49 64 81]
[  1   4   9  16  25  36  49  64  81 100]
[ 0  1  4  9 16]
[ 4 36]
[ 0  4 16 36 64]
[100  81  64  49  36  25  16   9   4   1   0]
